language: python
python: # => 2
  - "3.6"
services: # => 3
  - postgresql
install: # => 5
  - pip install -r requirements.txt
before_script: # => 6
  - psql -c 'create database travis_ci_test;' -U postgres
script: # => 7
  - python manage.py test