INSERT INTO inventorymanagement_record VALUES('SAP(Tech)','ammonia','PC')
INSERT INTO inventorymanagement_record VALUES('Fatima al katheri','','PC')
INSERT INTO inventorymanagement_record VALUES('Utility Day Sup','OP','PC')
INSERT INTO inventorymanagement_record VALUES('LAB / Fatima alamri','LAB','PC')
INSERT INTO inventorymanagement_record VALUES('Shrikant Umale','Ele','PC')
INSERT INTO inventorymanagement_record VALUES('Suresh Sonavane','Ele','PC')
INSERT INTO inventorymanagement_record VALUES('LAB / General Shift','LAB','PC')
INSERT INTO inventorymanagement_record VALUES('Awadh alshanfari','MD','PC')
INSERT INTO inventorymanagement_record VALUES('Utility shift sup','OP','PC')
INSERT INTO inventorymanagement_record VALUES('Praseed','WH','PC')
INSERT INTO inventorymanagement_record VALUES('Maxim','Main','PC')
INSERT INTO inventorymanagement_record VALUES('Ahmed Nawaz','Inst','PC')
INSERT INTO inventorymanagement_record VALUES('Sami al qaiti','Muscat /HR','PC')
INSERT INTO inventorymanagement_record VALUES('Noor Bait Said','Fin','PC')
INSERT INTO inventorymanagement_record VALUES('Lamia Salem','Fin','PC')
INSERT INTO inventorymanagement_record VALUES('Kawkab','Mech','PC')
INSERT INTO inventorymanagement_record VALUES('security','security','PC')
INSERT INTO inventorymanagement_record VALUES('Malik AL ghili','Inst','PC')
INSERT INTO inventorymanagement_record VALUES('Abdullah.bahajjaj','HR','PC')
INSERT INTO inventorymanagement_record VALUES('Moazzam Ali','Mech','PC')
INSERT INTO inventorymanagement_record VALUES('Renjjan Thankachan','Mech','PC')
INSERT INTO inventorymanagement_record VALUES('Morgan','Reli','PC')
INSERT INTO inventorymanagement_record VALUES('Abdulqader','ELe','PC')
INSERT INTO inventorymanagement_record VALUES('Said al Awaid','Inst','PC')
INSERT INTO inventorymanagement_record VALUES('headcount / nooh','HSE','PC')
INSERT INTO inventorymanagement_record VALUES('Ghadha alshanfari','Tech','PC')
INSERT INTO inventorymanagement_record VALUES('Irsad','Min','Laptop')
INSERT INTO inventorymanagement_record VALUES('laila Bait said','Performance','Laptop')
INSERT INTO inventorymanagement_record VALUES('Ammonia (teinee)','Ammonia','Laptop')
INSERT INTO inventorymanagement_record VALUES('Ajay','Electrecal','Laptop')
INSERT INTO inventorymanagement_record VALUES('Yaseer albathari','EA','Laptop')
INSERT INTO inventorymanagement_record VALUES('Ali al Barami','HR','Laptop')
INSERT INTO inventorymanagement_record VALUES('Umair','Fin','Laptop')
INSERT INTO inventorymanagement_record VALUES('Mani','Reli','Laptop')
INSERT INTO inventorymanagement_record VALUES('Ammar Qatan','Ammonia','Laptop')
INSERT INTO inventorymanagement_record VALUES('Mohammed al Hashmi','Opr','Laptop')
INSERT INTO inventorymanagement_record VALUES('Mishra','Opra','Laptop')
INSERT INTO inventorymanagement_record VALUES('Ahmed Muqaibl','','Laptop')
INSERT INTO inventorymanagement_record VALUES('Fatima al Shanfari (committee)','Tech','Laptop')
INSERT INTO inventorymanagement_record VALUES('Malik Eid','Fin','Laptop')
INSERT INTO inventorymanagement_record VALUES('saad al Minhali','HSE','Laptop')
INSERT INTO inventorymanagement_record VALUES('Zaheer Ahmed','Ins','Laptop')
INSERT INTO inventorymanagement_record VALUES('Srinivasan N','Reli','Laptop')
INSERT INTO inventorymanagement_record VALUES('ali al Zawamri','Reli','Laptop')
INSERT INTO inventorymanagement_record VALUES('(INDUCTION)','HSE','Laptop')
INSERT INTO inventorymanagement_record VALUES('Hussain  al Ojili','HR','Laptop')
INSERT INTO inventorymanagement_record VALUES('Amit','Per','PC')
INSERT INTO inventorymanagement_record VALUES('Nooh Suroor','security','PC')
INSERT INTO inventorymanagement_record VALUES('Mohammed Bin Zain','Per','PC')
INSERT INTO inventorymanagement_record VALUES('LAB','LAB','PC')
INSERT INTO inventorymanagement_record VALUES('Ahmed Khawar','Per','PC')
INSERT INTO inventorymanagement_record VALUES('Salim AlAamri','Per','PC')
INSERT INTO inventorymanagement_record VALUES('Tiwari','Per','PC')
INSERT INTO inventorymanagement_record VALUES('Abdullah Bhdoor','Ext A','PC')
INSERT INTO inventorymanagement_record VALUES('Jamal al Blushi','Ext A','PC')
INSERT INTO inventorymanagement_record VALUES('Amna','Ext A','PC')
INSERT INTO inventorymanagement_record VALUES('Majid Khan','IT','PC')
INSERT INTO inventorymanagement_record VALUES('Suresh','Ele','PC')
INSERT INTO inventorymanagement_record VALUES('mohamad alnahdi','Ext A','PC')
INSERT INTO inventorymanagement_record VALUES('deepak','opretion','PC')
INSERT INTO inventorymanagement_record VALUES('Subhash ','Planning','PC')
INSERT INTO inventorymanagement_record VALUES('Sameeh','HSE','PC')
INSERT INTO inventorymanagement_record VALUES('hassan al Barami','Planning','PC')
INSERT INTO inventorymanagement_record VALUES('Jude','Ins','PC')
INSERT INTO inventorymanagement_record VALUES('Mishra','Ins','PC')
INSERT INTO inventorymanagement_record VALUES('Reliability Room','Reli','PC')
INSERT INTO inventorymanagement_record VALUES('ANN NOMAN','EXC','PC')
INSERT INTO inventorymanagement_record VALUES('Shahid Shah','Mech','PC')
INSERT INTO inventorymanagement_record VALUES('khalid Aideed','Reception','PC')
INSERT INTO inventorymanagement_record VALUES('Rakesh Saxena','LAB','PC')
INSERT INTO inventorymanagement_record VALUES('Kiran Varma','Mech','PC')
INSERT INTO inventorymanagement_record VALUES('Abdullah Al-Rawas','Tech','PC')
INSERT INTO inventorymanagement_record VALUES('Eidroos','M&SH','Laptop')
INSERT INTO inventorymanagement_record VALUES('LAB','LAB','Laptop')
INSERT INTO inventorymanagement_record VALUES('Amira Tabook','Per','Laptop')
INSERT INTO inventorymanagement_record VALUES('Zuberi.hubib','Opra','Laptop')
INSERT INTO inventorymanagement_record VALUES('Ahmed Kashoub','Ext.A','Laptop')
INSERT INTO inventorymanagement_record VALUES('MUNDHER AL SHANFARI','MARKETING','Laptop')
INSERT INTO inventorymanagement_record VALUES('ASISH','INST','Laptop')
INSERT INTO inventorymanagement_record VALUES('Mohammed Kalshat','Admin','Laptop')
INSERT INTO inventorymanagement_record VALUES('Hamza al Rawas','Per','Laptop')
INSERT INTO inventorymanagement_record VALUES('LAYLA.ALSHAHRI','Ext.A','Laptop')
INSERT INTO inventorymanagement_record VALUES('Raid baznbour','HSE','Laptop')
INSERT INTO inventorymanagement_record VALUES('Manoj.c','Planinig','Laptop')
INSERT INTO inventorymanagement_record VALUES('fatik al Balushi','Fin','Laptop')
INSERT INTO inventorymanagement_record VALUES('Nitin','Ele','Laptop')
INSERT INTO inventorymanagement_record VALUES('Ali Ahmed ALShahari','Opra','Laptop')
INSERT INTO inventorymanagement_record VALUES('SOUD AL KATHIRI','Ext.A','Laptop')
INSERT INTO inventorymanagement_record VALUES('A.Samy','Reli','Laptop')
INSERT INTO inventorymanagement_record VALUES('Ahmed al Mashani','HSE','Laptop')
INSERT INTO inventorymanagement_record VALUES('Rakesh Saxena','Lab','Laptop')
INSERT INTO inventorymanagement_record VALUES('Kiran varma','Mech','Laptop')
INSERT INTO inventorymanagement_record VALUES('Abdullah AL Rawas','Tech','Laptop')
INSERT INTO inventorymanagement_record VALUES('Omaima','EXC','PC')
INSERT INTO inventorymanagement_record VALUES('LAB','LAB','PC')
INSERT INTO inventorymanagement_record VALUES('LAB','LAB','PC')
INSERT INTO inventorymanagement_record VALUES('fire room','HSE','PC')
INSERT INTO inventorymanagement_record VALUES('STG','STG','PC')
INSERT INTO inventorymanagement_record VALUES('Methanol Shelter','PRO','PC')
INSERT INTO inventorymanagement_record VALUES('Ali AL Amri','HSE','PC')
INSERT INTO inventorymanagement_record VALUES('TA Gate','HSE','PC')
INSERT INTO inventorymanagement_record VALUES('Clinic','HSE','PC')
INSERT INTO inventorymanagement_record VALUES('TA Gate','HSE','PC')
INSERT INTO inventorymanagement_record VALUES('abulRaufe','planning','PC')
INSERT INTO inventorymanagement_record VALUES('George Kutty','Mint','PC')
INSERT INTO inventorymanagement_record VALUES('Mazid Al Rawas','Extrnal','Laptop')
INSERT INTO inventorymanagement_record VALUES('Mashal','IT','Laptop')
INSERT INTO inventorymanagement_record VALUES('Mundher Monitor','M&SH','Laptop')
INSERT INTO inventorymanagement_record VALUES('IT _ Abdullah','IT','Laptop')
INSERT INTO inventorymanagement_record VALUES('Yousif Bamokalif','Mech','Laptop')
INSERT INTO inventorymanagement_record VALUES('Munira alAmri','tech','Laptop')
INSERT INTO inventorymanagement_record VALUES('Ali  Hubais','Per','Laptop')
