INSTALLED_APPS = [
    'inventoryManagement.apps.InventorymanagementConfig',
    'import_export',
    'simple_history',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'debug_toolbar',
]