# Generated by Django 2.0.5 on 2018-07-10 18:18

import django.core.validators
from django.db import migrations
import inventoryManagement.modelFiles.CustomCharField


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelist',
            name='deviceName',
            field=inventoryManagement.modelFiles.CustomCharField.UpperCaseCharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
    ]
