# Generated by Django 2.0.5 on 2018-07-08 06:48

import django.core.validators
from django.db import migrations
import inventoryManagement.modelFiles.CustomCharField


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0002_auto_20180705_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='department',
            field=inventoryManagement.modelFiles.CustomCharField.UpperCaseCharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='department',
            field=inventoryManagement.modelFiles.CustomCharField.UpperCaseCharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
    ]