# Generated by Django 2.0.5 on 2018-07-03 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0011_record_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='deviceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'List Of Devices',
            },
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventoryManagement.deviceList', to_field='deviceName'),
        ),
        migrations.AlterField(
            model_name='record',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryManagement.deviceList', to_field='deviceName'),
        ),
    ]