# Generated by Django 2.0.5 on 2018-07-03 11:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0011_record_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='deviceList',
            fields=[
                ('deviceName', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')])),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'List Of Devices',
            },
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='department',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventoryManagement.deviceList'),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='location',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='name',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='department',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryManagement.deviceList'),
        ),
        migrations.AlterField(
            model_name='record',
            name='location',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
    ]