# Generated by Django 2.0.5 on 2018-05-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('device', models.CharField(choices=[('pc', 'Personal Computer'), ('lt', 'Laptop')], default='pc', max_length=2)),
            ],
        ),
    ]
