# Generated by Django 2.0.5 on 2018-05-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0003_auto_20180522_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='department',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='device',
            field=models.CharField(choices=[('pc', 'Personal Computer'), ('lt', 'Laptop')], default='pc', max_length=2),
        ),
        migrations.AddField(
            model_name='record',
            name='year',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=4),
            preserve_default=False,
        ),
    ]
