# Generated by Django 2.0.5 on 2018-06-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0006_historicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='recordSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Department Inventory',
                'verbose_name_plural': 'Departments Inventory',
                'proxy': True,
                'indexes': [],
            },
            bases=('inventoryManagement.record',),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='device',
            field=models.CharField(choices=[('pc', 'Personal Computer'), ('lt', 'Laptop'), ('aio', 'All In One')], default='pc', max_length=3),
        ),
        migrations.AlterField(
            model_name='record',
            name='device',
            field=models.CharField(choices=[('pc', 'Personal Computer'), ('lt', 'Laptop'), ('aio', 'All In One')], default='pc', max_length=3),
        ),
    ]
