# Generated by Django 2.0.5 on 2018-06-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0008_auto_20180612_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='device',
            field=models.CharField(choices=[('Personal Computer', 'Personal Computer'), ('Laptop', 'Laptop'), ('All In One', 'All In One')], default='Personal Computer', max_length=20),
        ),
    ]