# Generated by Django 2.0.5 on 2018-05-22 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0004_auto_20180522_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='year',
            field=models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(2016)]),
        ),
    ]
