# Generated by Django 2.0.5 on 2018-06-12 09:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0007_auto_20180601_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalrecord',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Record Of Inventory'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Record Of Inventory', 'verbose_name_plural': 'Records Of Inventory'},
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='device',
            field=models.CharField(choices=[('Personal Computer', 'Personal Computer'), ('Laptop', 'Laptop'), ('All In One', 'All In One')], default='Personal Computer', max_length=20),
        ),
    ]