# Generated by Django 2.0.5 on 2018-06-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0009_auto_20180620_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecord',
            name='location',
            field=models.CharField(default='smc', max_length=50),
            preserve_default=False,
        ),
    ]
