# Generated by Django 2.0.5 on 2018-07-03 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0012_auto_20180703_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelist',
            name='deviceName',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='department',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='location',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='department',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='location',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
    ]