# Generated by Django 2.0.5 on 2018-05-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='year',
            field=models.DecimalField(decimal_places=0, default=2018, max_digits=4),
            preserve_default=False,
        ),
    ]
