# Generated by Django 2.0.5 on 2018-07-05 08:06

import django.core.validators
from django.db import migrations
import inventoryManagement.modelFiles.CustomCharField


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelist',
            name='deviceName',
            field=inventoryManagement.modelFiles.CustomCharField.TitleCaseCharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='department',
            field=inventoryManagement.modelFiles.CustomCharField.TitleCaseCharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='location',
            field=inventoryManagement.modelFiles.CustomCharField.TitleCaseCharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='name',
            field=inventoryManagement.modelFiles.CustomCharField.TitleCaseCharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='department',
            field=inventoryManagement.modelFiles.CustomCharField.TitleCaseCharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='location',
            field=inventoryManagement.modelFiles.CustomCharField.TitleCaseCharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=inventoryManagement.modelFiles.CustomCharField.TitleCaseCharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_text', message='The text must start with, and end with, a alphanumeric character. There should NOT be any consecutive spaces too.', regex='^([a-zA-Z0-9]+\\s)*[a-zA-Z0-9]+$')]),
        ),
    ]